"""create_cost_categories_table

Revision ID: 0f010eeb80e9
Revises: cd5e754e3779
Create Date: 2026-07-20 02:23:55.236628
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0f010eeb80e9'
down_revision: str | None = 'cd5e754e3779'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cost_categories",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "display_order",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name="fk_cost_categories_event_id_events"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_categories")),
    )
    op.create_index(
        op.f("ix_cost_categories_event_id"), "cost_categories", ["event_id"], unique=False
    )
    # Non-archived names unique within an event (business_rules.md). Soft-deleted
    # rows may reuse names.
    op.create_index(
        "uq_cost_categories_event_id_name_active",
        "cost_categories",
        ["event_id", "name"],
        unique=True,
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_cost_categories_event_id_name_active",
        table_name="cost_categories",
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.drop_index(op.f("ix_cost_categories_event_id"), table_name="cost_categories")
    op.drop_table("cost_categories")
    # ### end Alembic commands ###
