"""create_cost_items_and_versions

Revision ID: 3d8b49e64329
Revises: 0f010eeb80e9
Create Date: 2026-07-20 02:38:15.129092
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3d8b49e64329'
down_revision: str | None = '0f010eeb80e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_items',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expense_type', sa.Enum('Vendor', 'Internal', 'Shared', name='expense_type', native_enum=False, length=32), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('negotiated_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('vendor_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('Planned', 'Approved', 'In Progress', 'Completed', 'Cancelled', name='cost_item_status', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['cost_categories.id'], name='fk_cost_items_category_id_cost_categories'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_cost_items_event_id_events'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_items'))
    )
    op.create_index(op.f('ix_cost_items_category_id'), 'cost_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_cost_items_event_id'), 'cost_items', ['event_id'], unique=False)
    op.create_index(op.f('ix_cost_items_status'), 'cost_items', ['status'], unique=False)
    op.create_table('cost_item_versions',
    sa.Column('cost_item_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('negotiated_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cost_item_id'], ['cost_items.id'], name='fk_cost_item_versions_cost_item_id_cost_items'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_item_versions'))
    )
    op.create_index(op.f('ix_cost_item_versions_cost_item_id'), 'cost_item_versions', ['cost_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_item_versions_cost_item_id'), table_name='cost_item_versions')
    op.drop_table('cost_item_versions')
    op.drop_index(op.f('ix_cost_items_status'), table_name='cost_items')
    op.drop_index(op.f('ix_cost_items_event_id'), table_name='cost_items')
    op.drop_index(op.f('ix_cost_items_category_id'), table_name='cost_items')
    op.drop_table('cost_items')
    # ### end Alembic commands ###
